#!/bin/bash

for f in `ls -S /home/downloads/ok/*.avi` ; do 
	name=`basename $f .avi`

	ffmpeg -y -threads 5 -i /home/downloads/ok/$name.avi -vcodec libx264 -acodec libfaac -ac 2 -b 512k -vpre hq /home/downloads/mp4/$name-temp.mp4

	qt-faststart /home/downloads/mp4/$name-temp.mp4 /home/downloads/ok/$name.mp4

	rm /home/downloads/mp4/$name-temp.mp4
done
